export const ON_NEXT_PAGE = 'ON_NEXT_PAGE';
export const ON_NEXT_PAGE_CANCEL = 'ON_NEXT_PAGE_CANCEL';

export const ON_FIRST_BUBBLE_STATE = "ON_FIRST_BUBBLE_STATE";
export const ON_SECOND_BUBBLE_STATE = "ON_SECOND_BUBBLE_STATE";
export const ON_THIRD_BUBBLE_STATE = "ON_THIRD_BUBBLE_STATE";
export const ON_ALL_BUBBLE_DONE = "ON_ALL_BUBBLE_DONE";

export const ON_SUBMIT_PASS = "ON_SUBMIT_PASS";
export const ON_SUBMIT_PASS2 = "ON_SUBMIT_PASS2";
export const ON_SUBMIT_PISTA = "ON_SUBMIT_PISTA";
export const ON_PASS_EMPTY = "ON_PASS_EMPTY";
export const ON_PASS2_EMPTY = "ON_PASS2_EMPTY";
export const ON_PISTA_EMPTY = "ON_PISTA_EMPTY";

export const ON_SUBMIT_OK = "ON_SUBMIT_OK";
export const ON_SUBMIT_NOT = "ON_SUBMIT_NOT";
export const ON_ALL_CANCEL = "ON_ALL_CANCEL";